apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: postgres
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: postgres
data:
  init.sql: |
    CREATE DATABASE nextcloud;
    CREATE USER nextcloud WITH PASSWORD '${NEXTCLOUD_DB_PASSWORD_PLAIN}';
    GRANT ALL PRIVILEGES ON DATABASE nextcloud TO nextcloud;