apiVersion: v1
kind: Service
metadata:
  name: postgres-external
  namespace: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      name: psql
  type: ExternalName
  externalName: postgres.postgres.svc.cluster.local

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-nodeport
  namespace: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 31384
      name: psql
  type: NodePort