apiVersion: v1
kind: PersistentVolumeClain
metadata:
  name: postgres-pvc
  namespace: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ssd
  volumeName: postgres-pv-volume