apiVersion: batch/v1
kind: CronJob
metadata:
  name: parking-reservation
  namespace: cronjobs
spec:
  schedule: "15 00 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: parking-reservation
            image: docker.spof.tech/spof/parking-reservation:latest
            pullPolicy: IfNotPresent
          restartPolicy: Never
          concurrencyPolicy: Forbid
          imagePullSecrets:
          - name: docker-registry-cred
      backoffLimit: 0
