apiVersion: batch/v1
kind: CronJob
metadata:
  name: parking-reservation
  namespace: cronjobs
spec:
  schedule: "15 00 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: parking-reservation
            image: registry.spof.tech/parking-reservation:latest
            pullPolicy: IfNotPresent
          restartPolicy: OnFailure
