apiVersion: v1
kind: Secret
metadata:
  name: gh-actions-user-secret
  namespace: gh-actions
  annotations:
    kubernetes.io/service-account.name: gh-actions-user
type: kubernetes.io/service-account-token