apiVersion: apps/v1
kind: Deployment
metadata:
  name: owncloud
  namespace: owncloud
  labels:
    app: owncloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: owncloud
  template:
    metadata:
      labels:
        app: owncloud
    spec:
      containers:
      - name: owncloud
        image: owncloud/server:latest
        env:
          - name: TZ
            value: Europe/Berlin
          - name: DEBUG
            value: "false"

          - name: OWNCLOUD_URL
            value: https://cloud.spof.tech

          - name: OWNCLOUD_ADMIN_USER
            value: admin
          - name: OWNCLOUD_ADMIN_PASSWORD
            value: ${OWNCLOUD_ADMIN_PASS} 

          - name: OWNCLOUD_UPLOAD_MAX_FILESIZE
            value: 10G
          - name: OWNCLOUD_MAX_FILE_UPLOADS
            value: "1000"

          - name: DB_TYPE
            value: pgsql
          - name: DB_HOST
            value: postgresql
          - name: DB_PORT
            value: "5432"
          - name: DB_USER
            value: owncloud
          - name: DB_PASS
            value: ${OWNCLOUD_DB_PASS} 
          - name: DB_NAME
            value: owncloud_db

        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: "/mnt/data"
          name: data


      - name: postgresql
        image: postgresql:latest
        env:
          - name: DB_USER
            value: owncloud
          - name: DB_PASS
            value: ${OWNCLOUD_DB_PASS} 
          - name: DB_NAME
            value: owncloud_db
        ports:
          - containerPort: 5432
            protocol: TCP
        volumeMounts:
          - mountPath: /var/lib/postgresql
            name: owncloud-db


      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: owncloud-pvc
      - name: owncloud-db
        persistentVolumeClaim:
          claimName: owncloud-db-pvc