# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mosquitto-config
#   namespace: mosquitto
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 15Mi
#   storageClassName: ssd

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-data
  namespace: mosquitto
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: ssd

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-log
  namespace: mosquitto
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
  storageClassName: ssd

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-certs
  namespace: mosquitto
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: ssd