apiVersion: v1
kind: ConfigMap
metadata:
  name: ntfy
  namespace: ntfy
data:
  server.yml: |
    base-url: "https://ntfy.spof.tech"
    listen-http: ":80"
    listen-https: ":443"
    key-file: "/etc/letsencrypt/live/tls.key"
    cert-file: "/etc/letsencrypt/live/tls.crt"
    cache-file: "/var/cache/ntfy/cache.db"
    attachment-cache-dir: "/var/cache/ntfy/attachments"