
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb 
  namespace: nextcloud
  labels:
    app: mariadb 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb 
  template:
    metadata:
      labels:
        app: mariadb 
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      volumes:
      - name: mariadb-data
        persistentVolumeClaim:
          claimName: mariadb-pvc
      containers:
      - name: mariadb 
        image: mariadb:latest 
        ports:
          - containerPort: 3306 
        args:
          - --transaction-isolation=READ-COMMITTED
          - --binlog-format=ROW
          - --max-connections=1000
        env:
            - name: MYSQL_DATABASE
              value: nextcloud
            - name: MYSQL_PASSWORD
              value: ${NEXTCLOUD_DB_PASSWORD}
            - name: MYSQL_USER
              value: nextcloud
            - name: MYSQL_ROOT_PASSWORD
              value: ${NEXTCLOUD_DB_PASSWORD}
        volumeMounts:
        - name: mariadb-data
          mountPath: /var/lib/mysql

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud 
  namespace: nextcloud
  labels:
    app: nextcloud 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud 
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      volumes:
      - name: nextcloud-storage
        persistentVolumeClaim: 
          claimName: nextcloud-pvc
      containers:
        - image: nextcloud:apache
          name: nextcloud 
          ports:
            - containerPort: 80
          env:
            # - name: REDIS_HOST
            #   value: redis
            - name: MYSQL_HOST
              value: mariadb 
            - name: MYSQL_DATABASE
              value: nextcloud
            - name: MYSQL_PASSWORD
              value: ${NEXTCLOUD_DB_PASSWORD}
            - name: MYSQL_USER
              value: nextcloud
            - name: NEXTCLOUD_ADMIN_PASSWORD
              value: ${NEXTCLOUD_ADMIN_PASSWORD}
            - name: NEXTCLOUD_ADMIN_USER
              value: "admin"
            - name: NEXTCLOUD_TRUSTED_DOMAINS 
              value: cloud.spof.tech
          volumeMounts:
            - mountPath: /var/www/html
              name: nextcloud-storage