apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud 
  namespace: nextcloud
  labels:
    app: nextcloud 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud 
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
        node-role.kubernetes.io/master: "true"
      volumes:
      - name: mariadb-data
        persistentVolumeClaim:
          claimName: mariadb-pvc
      - name: nextcloud-storage
        persistentVolumeClaim: 
          claimName: nextcloud-pvc
      containers:
      - name: mariadb 
        image: mariadb:latest
        ports:
          - containerPort: 3306
        env:
          - name: TZ
            value: Europe/Berlin
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: MYSQL_DATABASE
            value: nextcloud
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nextcloud-secret
                key: mariadb-password
          - name: MYSQL_USER
            value: nextcloud
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nextcloud-secret
                key: mariadb-root-password
          - name: PHP_UPLOAD_LIMIT
            value: "10G"
        volumeMounts:
        - name: mariadb-data
          mountPath: /var/lib/mysql

      - image: nextcloud
        name: nextcloud 
        ports:
          - containerPort: 80
            protocol: TCP
        env:
          - name: TZ
            value: Europe/Berlin
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: MYSQL_HOST
            value: "nextcloud-db:3306"
          - name: MYSQL_DATABASE
            value: nextcloud
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nextcloud-secret
                key: mariadb-password
          - name: MYSQL_USER
            value: nextcloud
          - name: NEXTCLOUD_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nextcloud-secret
                key: nextcloud-password
          - name: NEXTCLOUD_ADMIN_USER
            value: "admin"
          - name: NEXTCLOUD_TRUSTED_DOMAINS 
            value: cloud.spof.tech
          - name: OVERWRITEHOST
            value: cloud.spof.tech
          - name: OVERWRITEPROTOCOL
            value: https
          - name: OVERWRITECLIURL
            value: https://cloud.spof.tech
          - name: TRUSTED_PROXIES
            value: "192.168.178.0/24 10.42.0.0/24 10.42.1.0/24 10.42.2.0/24 10.43.0.0/16"
          - name: NEXTCLOUD_URL
            value: https://cloud.spof.tech
        volumeMounts:
          - mountPath: /var/www/html
            name: nextcloud-storage