apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
  namespace: nextcloud
type: Opaque
data:
  MYSQL_PASSWORD: $(echo -n ${NEXTCLOUD_DB_PASSWORD} | base64)
  NEXTCLOUD_ADMIN_PASSWORD: $(echo -n ${NEXTCLOUD_ADMIN_PASSWORD} | base64)