apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
  namespace: nextcloud
type: Opaque
data:
  db-password: ${NEXTCLOUD_DB_PASSWORD}
  # mariadb-root-password: ${NEXTCLOUD_DB_ROOT_PASSWORD}
  nextcloud-password: ${NEXTCLOUD_ADMIN_PASSWORD}