apiVersion: v1
kind: Service
metadata:
  name: nextcloud-db
  namespace: nextcloud
  labels:
    app: mariadb
spec:
  ports:
    - port: 3306
      protocol: TCP
  selector:
    app: nextcloud
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud 
  namespace: nextcloud
  labels:
    app: nextcloud
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
      protocol: TCP
  selector:
    app: nextcloud