apiVersion: v1
kind: ConfigMap
metadata:
  name: homeassistant-config
  namespace: homeassistant
data:
  configuration.yaml: |
    # Loads default set of integrations. Do not remove.
    default_config:

    # Text to speech
    tts:
      - platform: google_translate

    http:
      use_x_forwarded_for: true
      trusted_proxies: 
        - 10.42.0.0/16

    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml