apiVersion: v1
kind: ConfigMap
metadata:
  name: homeassistant-config
  namespace: homeassistant
data:
  configuration.yaml: |
    # Loads default set of integrations. Do not remove.
    default_config:

    # Text to speech
    tts:
      - platform: google_translate

    # Proxy config for Ingress
    http:
      use_x_forwarded_for: true
      trusted_proxies: 
        - 10.42.0.0/16

    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml
  
  automations.yaml: |
    - id: '1'
      alias: Close Blinds
      description: ''
      trigger:
      - platform: time
        at: '18:00:00'
      condition: []
      action:
      - device_id: 4a1c6975f2400043d1ceec078839fec8
        domain: cover
        entity_id: cover.links
        type: set_position
        position: 0
      - device_id: 05a193663865ff9f6b3db33f85fda860
        domain: cover
        entity_id: cover.rechts
        type: set_position
        position: 0
      mode: single

  scripts.yaml: |

  scenes.yaml: |
  
