apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ha-pvc
  namespace: homeassistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ssd

# ---

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: ha-mysql-pvc
#   namespace: homeassistant
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
#   storageClassName: ssd