apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/hostname: hp-elitedesk
      containers:
      - name: registry
        image: registry:latest
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: "/var/lib/registry"
          name: registry-pv
          subPath: "registry"
      volumes:
      - name: registry-pv
        persistentVolumeClaim:
          claimName: registry-pvc