apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: registry:latest
        ports:
        - containerPort: 443
        env:
        - name: REGISTRY_AUTH
          value: "htpasswd"
        - name: REGISTRY_AUTH_HTPASSWD_PATH
          value: /auth/htpasswd
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: /certs/tls.crt
        - name: REGISTRY_HTTP_TLS_KEY
          value: /certs/tls.key
        - name: REGISTRY_HTTP_ADDR
          value: "0.0.0.0:443"
        volumeMounts:
        - mountPath: "/var/lib/registry"
          name: registry-pv
          subPath: "registry"
        - mountPath: "/certs"
          name: certs
        - mountPath: "/auth"
          name: htpasswd
          readOnly: true
          subPath: "htpasswd"
      volumes:
      - name: registry-pv
        persistentVolumeClaim:
          claimName: registry-pvc
      - name: certs
        secret:
          secretName: registry-certs
      - name: htpasswd
        configMap:
          name: htpasswd