apiVersion: v1
kind: Service
metadata:
  name: registry-service
  namespace: registry
  labels:
    app: registry
spec:
  ports:
  - port: 443
    targetPort: 443
    name: registry
  selector:
    app: registry