apiVersion: v1
kind: Service
metadata:
  name: registry-service
  namespace: registry
  labels:
    app: registry
spec:
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30500
    name: registry
  type: NodePort
  selector:
    app: registry