apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: homeassistant
  name: homeassistant
  namespace: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      volumes:
        - name: ha-storage
          persistentVolumeClaim:
            claimName: ha-pvc
        - name: ha-config
          configMap:
            name: homeassistant-config
      containers:
        - image: ghcr.io/home-assistant/home-assistant:2022.12
          name: home-assistant
          volumeMounts:
            - mountPath: "/config"
              name: ha-storage
          ports:
            - containerPort: 8123
              name: http
              protocol: TCP
      initContainers:
        - name: init-homeassistant
          image: busybox
          command: ['/bin/sh', '-c']
          args: ['cp /config/configuration.yaml /config-ha/configuration.yaml; cp /config/automations.yaml /config-ha/automations.yaml; cp /config/scripts.yaml /config-ha/scripts.yaml; cp /config/scenes.yaml /config-ha/scenes.yaml']
          volumeMounts:
            - name: ha-config
              mountPath: /config
            - name: ha-storage
              mountPath: /config-ha


            