apiVersion: batch/v1
kind: CronJob
metadata:
  name: resale-saturday
  namespace: cronjobs
spec:
  # Every 5 minutes
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: resale-saturday
            image: docker.spof.tech/spof/pv23_resale_saturday:latest
            pullPolicy: IfNotPresent
          restartPolicy: Never
          concurrencyPolicy: Forbid
          imagePullSecrets:
          - name: recred
      backoffLimit: 0
