apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esphome-pvc
  namespace: homeassistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200m
  storageClassName: ssd