apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gh-actions-user
  namespace: gh-actions
rules:
- apiGroups:
  - ""
  - apps
  - autoscaling
  - batch
  - extensions
  - policy
  - rbac.authorization.k8s.io
  - networking.k8s.io
  - storage.k8s.io
  - apiextensions.k8s.io
  resources:
  - pods
  - services
  - serviceaccounts
  - ingresses
  - namespaces
  - clusterroles
  - configmaps
  - secrets
  - persistentvolumes
  - persistentvolumeclaims
  - deployments
  - replicasets
  - replicationcontrollers
  - roles
  - rolebindings
  - clusterrolebindings
  - cronjobs
  - jobs
  - daemonsets
  - certificates 
  - storageclasses
  - customresourcedefinition
  - networkpolicies
  - ingressclasses
  - validatingwebhookconfiguration
  - mutatingwebhookconfiguration

  verbs:
  - apply
  - delete
  - get
  - patch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gh-actions-user
  namespace: gh-actions
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gh-actions-user
subjects:
- kind: ServiceAccount
  name: gh-actions-user
  namespace: gh-actions