name: deploy

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
      # - ".github/*"

  workflow_dispatch:

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create kubeconfig
        run: |
          mkdir ${HOME}/.kube
          echo ${{ secrets.KUBECONFIG }} | base64 --decode > ${HOME}/.kube/config
          
      - name: Get changed files
        uses: tj-actions/changed-files@v25
        id: changed-files

      - name: Apply all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "applying $file"
            kubectl apply -f $file
          done
