name: Deploy All

on:
  workflow_dispatch:

jobs:
  kubectl-apply:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.get-files.outputs.files }}
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create kubeconfig
        run: |
          mkdir ${HOME}/.kube
          echo ${{ secrets.KUBECONFIG }} | base64 --decode > ${HOME}/.kube/config


      - name: Apply files
        uses: nick-fields/retry@v2
        env:
          NEXTCLOUD_ADMIN_PASSWORD: ${{ secrets.NEXTCLOUD_ADMIN_PASS }}
          NEXTCLOUD_DB_PASSWORD: ${{ secrets.NEXTCLOUD_DB_PASS }}
          NEXTCLOUD_DB_ROOT_PASSWORD: ${{ secrets.NEXTCLOUD_DB_ROOT_PASS }}
          HOMEASSISTANT_DB_PASSWORD: ${{ secrets.HOMEASSISTANT_DB_PASSWORD }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        with:
          timeout_seconds: 60
          max_attempts: 4
          command: |
            for f in */namespace.yaml; do
              envsubst < $f | kubectl apply -f -
            done

            for f in */*.yaml; do
              envsubst < $f | kubectl apply -f -
            done