name: Deploy All

on:
  workflow_dispatch:

jobs:
  get-files:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.get-files.outputs.files }}
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create kubeconfig
        run: |
          mkdir ${HOME}/.kube
          echo ${{ secrets.KUBECONFIG }} | base64 --decode > ${HOME}/.kube/config

      - name: Get files
        id: get-files
        run: |
          array=($(find . -name '*.yaml')) 
          liststring=$(printf "\\\\\"%s\\\\\", " "${array[@]}")
          list=${liststring::-2}
          echo $list
          echo "::set-output name=files::[$list]"

     
  apply:
    needs: get-files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{ fromJson(needs.get-files.outputs.files) }}
    steps:
      - name: Apply namespaces
        if: ${{ endsWith(matrix.value, 'namespace.yaml') }}
        run: |
          kubectl apply -f ${{ matrix.value }}

      - name: Apply all files  
        uses: nick-fields/retry@v2
        env:
          NEXTCLOUD_ADMIN_PASSWORD: ${{ secrets.NEXTCLOUD_ADMIN_PASS }}
          NEXTCLOUD_DB_PASSWORD: ${{ secrets.NEXTCLOUD_DB_PASS }}
          NEXTCLOUD_DB_ROOT_PASSWORD: ${{ secrets.NEXTCLOUD_DB_ROOT_PASS }}
          HOMEASSISTANT_DB_PASSWORD: ${{ secrets.HOMEASSISTANT_DB_PASSWORD }}
        with:
          timeout_seconds: 30
          max_attempts: 4
          command: |
            envsubst < ${{ matrix.value }} | kubectl apply -f -
