name: deploy

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create kubeconfig
        run: |
          mkdir ${HOME}/.kube
          echo ${{ secrets.KUBECONFIG }} > ${HOME}/.kube/config
          cat ${HOME}/.kube/config
