name: Deploy

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - ".github/**"

  workflow_dispatch:

jobs:
  kubectl-apply:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create kubeconfig
        run: |
          mkdir ${HOME}/.kube
          echo ${{ secrets.KUBECONFIG }} | base64 --decode > ${HOME}/.kube/config
          
      - name: Get changed files
        uses: tj-actions/changed-files@v25
        id: changed-files

      - name: Apply all changed files
        uses: nick-fields/retry@v2
        env:
          NEXTCLOUD_ADMIN_PASSWORD: ${{ secrets.NEXTCLOUD_ADMIN_PASS }}
          NEXTCLOUD_DB_PASSWORD: ${{ secrets.NEXTCLOUD_DB_PASS }}
          NEXTCLOUD_DB_ROOT_PASSWORD: ${{ secrets.NEXTCLOUD_DB_ROOT_PASS }}
          HOMEASSISTANT_DB_PASSWORD: ${{ secrets.HOMEASSISTANT_DB_PASSWORD }}
          WIFI_SSID: ${{ secrets.WIFI_SSID }}
          WIFI_PASSWORD: ${{ secrets.WIFI_PASSWORD }}
        with:
          timeout_seconds: 30
          max_attempts: 4
          command: |
            
            for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
              if [[ "$file" == ".github/"* ]]; then
                continue
              fi
              if [[ "$file" == *".yaml" ]]; then              
                echo "applying $file"
                envsubst < $file | kubectl apply -f -
              fi
            done
