name: Validate

on:
  pull_request:
    branches: [ "master" ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      name: Checkout repository
      with:
        fetch-depth: 0
        
    - name: Get changed files
      uses: tj-actions/changed-files@v25
      id: changed-files
      with:
        files_separator: ","
        dir_names: true
      
    - name: Validate Files
      id: validate-files
      uses: marcleibold/kubeval-action@master
      continue-on-error: true
      with:
        files: ${{ steps.changed-files.outputs.all_changed_files }}
      
    - name: Update Pull Request
      uses: actions/github-script@v5
      env:
        OUTPUT: "${{ steps.validate-files.outputs.all }}"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = `#### Validation Results
          \`\`\`\n
          ${process.env.OUTPUT}
          \`\`\`
          *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })